/** Rupert UX microcopy — direct, adversarial, action-first. */

export const copy = {
  brand: {
    name: "Rupert",
    tagline: "Viability engine",
    subtitle: "Stress-test ideas before you build.",
  },
  landing: {
    headline: "Your idea won't survive this.",
    description:
      "Stress-test startup ideas before you build. No cheerleading. Your keys stay in this browser.",
    cta: "Stress-test an idea",
    ctaHint: "Sign in to run your first test",
    principles: ["Zero sycophancy", "Seven dimensions", "Instant kill triggers"] as const,
    footer: "Adversarial by design",
    sampleVerdict: "Sample verdict",
    sampleIdea: "AI for everything",
    sampleSummary:
      "No buyer, no wedge, no reason this exists. A thin wrapper on someone else's model.",
    sampleBadge: "Hard no-go",
    killTriggers: "Kill trigger status",
    dimensions: "Dimension scores",
    triggered: "Triggered",
    cleared: "Cleared",
  },
  auth: {
    title: "Sign in to Rupert",
    subtitle: "Use email or a connected account.",
    google: "Continue with Google",
    github: "Continue with GitHub",
    emailDivider: "Or use email",
    emailLabel: "Email",
    emailPlaceholder: "you@company.com",
    sendCode: "Send verification code",
    codeSent: (email: string) => `We sent a code to ${email}.`,
    codeLabel: "Verification code",
    codePlaceholder: "123456",
    continue: "Continue",
    differentEmail: "Use a different email",
    resendCode: "Resend code",
    termsPrefix: "By continuing, you agree to Rupert's",
    termsLink: "Terms of Use",
    privacyLink: "Privacy Policy",
    errorEmailRequired: "Enter an email address.",
    errorCodeRequired: "Enter the verification code.",
    notConfiguredTitle: "Sign-in isn't configured",
    notConfiguredBody:
      "This host is missing Clerk keys. Add NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY and CLERK_SECRET_KEY, then redeploy.",
  },
  dashboard: {
    providerReady: "Ready",
    providerNoKey: "No API key",
    providerLabel: (provider: string, model: string) => `${provider} · ${model}`,
    newIdea: "New idea",
    errorNoKey: "Add an API key in Settings before you run a stress test.",
    errorGeneric: "Stress test failed. Check your provider settings and try again.",
    errorFileRead: "We couldn't read that file. Try another format.",
    stopped: "Stress test stopped",
    dismiss: "Dismiss",
    historyTitle: "Local history",
    historyEmpty: "No stress tests saved in this browser yet.",
    historyCompare: (a: string, scoreA: number, b: string, scoreB: number) =>
      `Last two: ${a} (${scoreA}) vs ${b} (${scoreB})`,
    historyDelete: "Delete",
  },
  mode: {
    form: "Form",
    chat: "Chat",
  },
  form: {
    title: "Red-team your idea",
    description: "Be specific. Vague inputs get vague verdicts.",
    run: "Run stress test",
    running: "Running stress test…",
    stop: "Stop",
    ideaName: "Idea or product name",
    industry: "Industry",
    industryPlaceholder: "Select industry",
    category: "Category",
    categoryPlaceholder: "Select category",
    industryDetail: "Industry detail (optional)",
    industryDetailPlaceholder: "e.g. InsurTech claims ops",
    targetCustomer: "Target customer (ICP)",
    problem: "Problem statement",
    problemPlaceholder: "Who loses time or money today? Put a number on it.",
    solution: "Solution and claimed moat",
    solutionPlaceholder: "Why isn't this a prompt or an incumbent feature?",
    monetization: "Monetization and delivery",
    alternatives: "Existing alternatives",
    priorEvidence: "Prior evidence (optional)",
    priorEvidencePlaceholder: "Research notes, calls, or MCP output. Treated as unverified.",
  },
  chat: {
    title: "Describe the idea",
    description: "Share what you know. Gaps stay unproven and will hurt the score.",
    empty: "Add notes or attach a file, then run the stress test.",
    placeholder: "What you know so far. Enter adds a note; Shift+Enter starts a new line.",
    addNote: "Add note",
  },
  file: {
    drop: "Drop a file to attach",
    reading: "Reading file…",
    choose: "Choose file",
    remove: "Remove",
  },
  scorecard: {
    composite: "Composite score",
    exportMd: "Export Markdown",
    exportJson: "Export JSON",
    matrix: "Seven-dimension stress matrix",
    onlyWay: "The only way this works",
    evidence: "Evidence pass",
    evidenceServers: (servers: string) => `Servers: ${servers || "none"}`,
    evidenceGaps: (gaps: string) => `Gaps: ${gaps}`,
    gates: "Pre-build validation gates",
    fatalFlaws: "Top fatal flaws",
    killTriggers: "Kill trigger status",
    redTeam: "Red team panel",
    coreAttack: "Core attack",
    requiredProof: "Required proof",
    gate: (n: number) => `Gate ${n}`,
    pass: (threshold: string) => `Pass: ${threshold}`,
    risk: (text: string) => `Risk: ${text}`,
    weight: (pct: number) => `${pct}% wt`,
    triggered: "Triggered",
    cleared: "Cleared",
  },
  settings: {
    title: "Settings",
    account: "Account",
    models: "Models",
    displayName: "Display name",
    signedIn: "Signed in",
    keysNote: "API keys stay in this browser and aren't stored on Rupert's servers.",
    provider: "Provider",
    apiKey: "API key (stored in this browser)",
    apiKeyOllama: "API key (optional for local, required for cloud)",
    apiKeyOllamaCloud: "Ollama Cloud key",
    model: "Model identifier",
    ollamaUrl: "Ollama base URL",
    ready: "Ready",
    noKey: "No key",
    saveConfig: "Save settings",
    mcpTitle: "MCP evidence (optional)",
    mcpHosted:
      "MCP evidence needs local stdio servers in ~/.rupert/mcp.json, which aren't available on this host.",
    mcpToggle:
      "Query servers in ~/.rupert/mcp.json before scoring. Off by default. Fail-open if a server is down.",
    mcpFilter: "Only these server names (comma-separated, blank = all enabled)",
    cancel: "Cancel",
    save: "Save settings",
    signOut: "Sign out",
    saveName: "Save name",
    loadingAccount: "Loading account…",
    nameSaved: "Name saved.",
    nameSaveFailed: "We couldn't save your name. Try again.",
    ollamaHostedKey:
      "Local Ollama isn't reachable from this hosted app. A key sends requests to ollama.com.",
    ollamaLocalKey: "A key always uses Ollama Cloud. Clear the key to use local Ollama.",
    ollamaKeyStored:
      "Stored in this browser for your account. Sent only with the current evaluation request. Never written to a remote store.",
    ollamaHostedUrl: "Use https://ollama.com. A local 127.0.0.1 URL won't work on this host.",
    ollamaLocalUrl:
      "Local is http://127.0.0.1:11434. Cloud is https://ollama.com. Not the /api path from the docs.",
    ollamaLocalLockedHosted: "Local Ollama isn't reachable on this host.",
    ollamaLocalLockedKey: "Clear the API key to use local Ollama.",
  },
  legal: {
    back: "Back to home",
  },
  nav: {
    privacy: "Privacy",
    terms: "Terms",
    signIn: "Sign in",
  },
} as const;
